---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          generate_release_notes: true
